### ISSUE TITLE
Don't change links that the user is about to click

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/try-gmt#47]
1. Visit https://github.com/GenericMappingTools/try-gmt
2. In the upper right corner, click the link https://mybinder.org/v2/gh/GenericMappingTools/try-gmt/master?urlpath=lab/tree/landing-page.ipynb
3. We see "Starting repository: GenericMappingTools/try-gmt/master ", and underneath it a link "New to Binder? Check out the [Binder Documentation](https://mybinder.readthedocs.io/en/latest/) for more information". But before we can read and comprehend and click the link, it has changed into something else! So frustrating!

**Comment by joa-quim** [comment]
I think that is not under our control but on Binder's itself.

**Comment by seisman** [comment]
Yes, there is nothing we can do. Closing the issue.
