### ISSUE TITLE
Add run GMT in bash instructions

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/try-gmt#48]
1. Visit https://github.com/GenericMappingTools/try-gmt
2. In the upper right corner, click the link https://mybinder.org/v2/gh/GenericMappingTools/try-gmt/master?urlpath=lab/tree/landing-page.ipynb
3. We end up on
![20230608T101249](https://github.com/GenericMappingTools/try-gmt/assets/1230959/83b758f3-b7fc-4366-b231-bb05556edeb5)

where near the bottom it says run GMT command in bash.

A file gets downloaded to our computer with no instructions.

**Comment by joa-quim** [comment]
I don't get any file downloaded to my computer. And not sure what you mean by *instructions*. Those of GMT? Well, we have quite extensive manuals, tutorials, examples at https://docs.generic-mapping-tools.org/latest/index.html

**Comment by jidanni** [comment]
Sorry! I now added steps 1 and 2 above.

**Comment by jidanni** [comment]
I see. One must wait for the top half of the page to fully load before clicking anything.
