### ISSUE TITLE
Google Colab Implementation

### ISSUE THREAD

**Issue by sarahshi** [GenericMappingTools/try-gmt#50]
Hi, 

Hope this message finds you well. I developed a teaching module using PyGMT back in February using [Google Colab](https://colab.research.google.com/github/sarahshi/earthchem-teaching/blob/main/SERC_MORB_colab.ipynb#scrollTo=NNzU5AQR8jrM). I used this described [solution](https://forum.generic-mapping-tools.org/t/colab-example-on-github-try-pygmt-online-not-working-any-more/1790/10
) to import PyGMT and things worked well. It sometimes took running the import cell another time -- some folks got an error upon first run -- but things worked successfully

I am currently preparing to teach this module again and just tried running through the code again. I am now getting the error appended. Do you know what may be causing this error? I didn't find any solutions on the forum and figured I may raise the issue here. Thanks in advance for any guidance. 

Best,
Sarah

```
---------------------------------------------------------------------------
GMTCLibNotFoundError                      Traceback (most recent call last)
[<ipython-input-2-9b6890099622>](https://localhost:8080/#) in <cell line: 8>()
      6 condacolab.install()
      7 get_ipython().system('mamba install pygmt')
----> 8 import pygmt
      9 from matplotlib import pyplot as plt
     10 get_ipython().run_line_magic('matplotlib', 'inline')

4 frames
[/usr/local/lib/python3.10/site-packages/pygmt/clib/loading.py](https://localhost:8080/#) in load_libgmt(lib_fullnames)
     57 
     58     if error:
---> 59         raise GMTCLibNotFoundError("\n".join(error_msg))
     60 
     61     return libgmt

GMTCLibNotFoundError: Error loading GMT shared library at '/usr/local/lib/libgmt.so'.
/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/local/lib/./libgdal.so.32)
Error loading GMT shared library at 'libgmt.so'.
libgmt.so: cannot open shared object file: No such file or directory
```

**Comment by seisman** [comment]
I just tried the PyGMT demo (https://colab.research.google.com/github/GenericMappingTools/try-gmt/blob/master/python-demo.ipynb) and it works well for me. So it means the solution still works.

**Comment by seisman** [comment]
Maybe you have to run the install commands in a separate cell? 
```
!pip install -q condacolab
import condacolab
condacolab.install()
```

**Comment by seisman** [comment]
> Maybe you have to run the install commands in a separate cell?
> 
> ```
> !pip install -q condacolab
> import condacolab
> condacolab.install()
> ```

Running the above commands in a separate cell works well for me.

**Comment by weiji14** [comment]
That error looks similar to https://github.com/GenericMappingTools/try-gmt/pull/37#issuecomment-1367074465, and I think is due to out of sync dependencies on conda-forge. Maybe the recent PRs like https://github.com/conda-forge/gmt-feedstock/pull/260 fixed it already?

**Comment by seisman** [comment]
Closing the issue as Google Colab works well for me.
