### ISSUE TITLE
New example to try pygmt on google colab.

### ISSUE THREAD

**Issue by andrebelem** [GenericMappingTools/try-gmt#52]
Hello,

After the new update in Google Colab (March 2024), it's possible to run conda install() and conda gmt/pygmt. I've updated my script and I'm using it with my students. Feel free to integrate it into the try-gmt.

https://github.com/andrebelem/pythonverse/blob/main/Using_pygmt_in_COLAB_[version_2023].ipynb

**Comment by seisman** [comment]
I think we already have similar instructions in our demo notebook https://github.com/GenericMappingTools/try-gmt/blob/master/python-demo.ipynb.

**Comment by andrebelem** [comment]
I believe we should specifically label the example as "COLAB" to help users find it easily.ly.

**Comment by seisman** [comment]
In 6c2754a24b98eaae06ce8bda261a81b51f5154c5, I've added an example notebook for Google Colab.
